### ISSUE TITLE
Few clarifications

### ISSUE THREAD

**Issue by vasnt** [Dhravya/cloudflare-saas-stack#12]
<img width="491" alt="image" src="https://github.com/user-attachments/assets/e0b31679-604b-4e5c-aa79-83c454bb565c">

1) Clone repo is not same as running given commands?
2) Wrangler needs to be installed within cloduflare-saas-stack directory?

**Comment by Dhravya** [comment]
1. Yeah, i added the command there just so that there's something easy to copy right away
2. it doesn't matter where wrangler is installed
