### ISSUE TITLE
how to upload an image?

### ISSUE THREAD

**Issue by javayhu** [Dhravya/cloudflare-saas-stack#23]
How can I upload an image? 

I already set env vars in dev.vars file and CORS policy in R2 settings, but failed to upload an image.

<img width="2239" alt="SCR-20240724-jjoh" src="https://github.com/user-attachments/assets/0902bd4b-d540-47ae-a24e-ca80b2f24f38">

<img width="1332" alt="SCR-20240724-jkfj" src="https://github.com/user-attachments/assets/cd67740a-90b3-4ec8-bbb5-3282954eee28">

**Comment by DiogoDuart3** [comment]
What does your cors policy looks like? 

It should look like this: 
![image](https://github.com/user-attachments/assets/5988bf41-b20d-4b7a-86f9-52398d2ae34a)

**Comment by CodeTorso** [comment]
> What does your cors policy looks like?
> 
> It should look like this:

We should actually try to make it easy. So that it works out of the box

**Comment by Dhravya** [comment]
More info about this in the new SETUP_GUIDE!
