### ISSUE TITLE
Deploy to Cloudflare

### ISSUE THREAD

**Issue by patrickgdl** [Dhravya/cloudflare-saas-stack#24]
Amazing work, man! Very good template.

Do you have your Cloudflare deployment working in Pages with GitHub integration?

I tried deploying it using the **root directory** like `apps/web`, but it always failed on `install`.

Then I saw that there is a script in `apps/web` (`pages:build`) for this. I created a new script in the root directory that pointed to `turborepo` to make it run.

The deployment works fine, but it appears to be missing the D1 database or have something wrong with `DrizzleAdapter`, perhaps because I'm now running in the root directory and it doesn't identify `wrangler.toml`? Have you ever seen something like this?

PS: If we make this work, I would love to help buid a guide/documentation to deploy this monorepo on Cloudflare

**Comment by patrickgdl** [comment]
Couldn't make it work :(

**Comment by patrickgdl** [comment]
I got it working putting `wrangler.toml` on root directory and changing `pages_build_output_dir`  to `apps/web/.vercel/output/static`. Closing it.

**Comment by CodeTorso** [comment]
hmmm that should have worked without doing anything

but thanks will modify it
