### ISSUE TITLE
Error while developing

### ISSUE THREAD

**Issue by crazyrunsnail** [Dhravya/cloudflare-saas-stack#25]
Hi, @Dhravya Thanks for you excellent works!
Everything is all right only while I runned in development mode with  `bun run dev`, and then i visited  the home page click `Login in google` and there is nothing happens , and I found there is a error in the console.

<img width="690" alt="Screenshot 2024-07-24 at 23 17 52" src="https://github.com/user-attachments/assets/ee476b00-fe14-478b-9302-2a378d693c4d">

OS: macos
Node: v20.12.0
Browser: both chrome and firefox are latest version

**Comment by crazyrunsnail** [comment]
> ids

Yes, I add it in the file `.dev.vars` and everythins is all right when i deploy to cf and add variable via the cf console. 

they  are same ids

**Comment by crazyrunsnail** [comment]
![image](https://github.com/user-attachments/assets/1cc1735f-ea32-447c-a0ba-c57a6fd538dd)

there is my `.dev.var`

**Comment by DiogoDuart3** [comment]
That error is related to hydration, and its caused by the themes package

**Comment by Dhravya** [comment]
Yeah, not sure how to fix that xD

**Comment by crazyrunsnail** [comment]
Can I just not use the theme?

**Comment by curtis-allan** [comment]
Can just add `suppressHydrationWarning` prop into the html tag in your `app/layout.tsx` file to remove the console warning in development

**Comment by crazyrunsnail** [comment]
@curtis-allan Thanks，It works. But I still get `[auth][error] TypeError: fetch failed`. Did you encounter this, any solutions?

**Comment by crazyrunsnail** [comment]
@curtis-allan Thanks, it works!
