### ISSUE TITLE
Issue: Dependency Conflict in Cloudflare Deployment

### ISSUE THREAD

**Issue by linguosity** [Dhravya/cloudflare-saas-stack#29]
Hello!

The next-auth package version 5.0.0-beta.19 requires next@14 or higher, but our project is using next@13.4.2. This causes a dependency conflict during the Cloudflare Pages deployment, resulting in a failed build. Is there a conflict between versions of Cloudfare and Next?

Thanks!

**Comment by Dhravya** [comment]
Yeah, we should upgrade to v14 and test it
