### ISSUE TITLE
Issue: D1 not storing authenticates users, empty.

### ISSUE THREAD

**Issue by Abood2284** [Dhravya/cloudflare-saas-stack#30]
I ran all the commands mentioned :
```
git clone https://github.com/Dhravya/cloudflare-saas-stack
cd cloudflare-saas-stack
npm i -g bun
bun install
bun run setup
```

On localHost, i am able to properly login, using google, and it properly displays how many users are in the DB:

<img width="350" alt="Screenshot 2024-07-26 at 11 29 31 AM" src="https://github.com/user-attachments/assets/aa43e88e-05a3-4d27-ad1b-2f3fa390e2b0">

But when I try to check my D1 database in my Cloudflare account, its empty:

<img width="706" alt="Screenshot 2024-07-26 at 11 30 35 AM" src="https://github.com/user-attachments/assets/c97b2b34-8383-4860-8b4d-a3e85968a1d7">

I have tried running this command : `bun run deploy`

it properly hosts my site on a random domain...

I have added that domain to my Google Cloud Console, but when i try to authenticate on the deployed domain, i get the following error:

<img width="594" alt="Screenshot 2024-07-26 at 11 32 01 AM" src="https://github.com/user-attachments/assets/39085a79-00a1-4f6d-aff4-ec0c773e2fa6">

What step am i missing?

**Comment by Abood2284** [comment]
<img width="1137" alt="Screenshot 2024-07-26 at 11 35 10 AM" src="https://github.com/user-attachments/assets/2ca014ae-4a59-4da2-ba8f-5d39cd22ca66">

this is the log recorded on the cloudflare :

`"message": [
        "\u001b[31m[auth][error]\u001b[0m MissingSecret: Please define a `secret`.. Read more at https://errors.authjs.dev#missingsecret"
      ],`
      
     .dev.vars file is present,
     
     created by `bun run setup` with proper values

**Comment by adamburmister** [comment]
Lurker: I saw similar behaviour with Env vars when in a middleware recently. I also saw a similar report on the CF discord today where Env vars go missing spending on how things are running. 

Maybe there's a clue there?

**Comment by Vette1123** [comment]
> <img alt="Screenshot 2024-07-26 at 11 35 10 AM" width="1137" src="https://private-user-images.githubusercontent.com/90205565/352395599-2ca014ae-4a59-4da2-ba8f-5d39cd22ca66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzkxMjQsIm5iZiI6MTcyMTk3ODgyNCwicGF0aCI6Ii85MDIwNTU2NS8zNTIzOTU1OTktMmNhMDE0YWUtNGE1OS00ZGEyLWJhOGYtNWQzOWNkMjJjYTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzAyZTRjOWI0ZTIyMDI4ZmYyNTNiNzYxYzc5NmVmNmUzMmU2NzQ5MDdiM2MxOGEyYjEwMWY2MTVlODA5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RDZzyAhqkaIRMluR5-UyRYLqDq-2HnvOkBRqcNOIbTY">
> this is the log recorded on the cloudflare :
> 
> `"message": [ "\u001b[31m[auth][error]\u001b[0m MissingSecret: Please define a `secret`.. Read more at https://errors.authjs.dev#missingsecret" ],`
> 
> ```
>  .dev.vars file is present,
>  
>  created by `bun run setup` with proper values
> ```

make .env.local file and add AUTH_SECRET=you-secret-key

**Comment by Abood2284** [comment]
> > <img alt="Screenshot 2024-07-26 at 11 35 10 AM" width="1137" src="https://private-user-images.githubusercontent.com/90205565/352395599-2ca014ae-4a59-4da2-ba8f-5d39cd22ca66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzkxMjQsIm5iZiI6MTcyMTk3ODgyNCwicGF0aCI6Ii85MDIwNTU2NS8zNTIzOTU1OTktMmNhMDE0YWUtNGE1OS00ZGEyLWJhOGYtNWQzOWNkMjJjYTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzAyZTRjOWI0ZTIyMDI4ZmYyNTNiNzYxYzc5NmVmNmUzMmU2NzQ5MDdiM2MxOGEyYjEwMWY2MTVlODA5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RDZzyAhqkaIRMluR5-UyRYLqDq-2HnvOkBRqcNOIbTY">
> > this is the log recorded on the cloudflare :
> > `"message": [ "\u001b[31m[auth][error]\u001b[0m MissingSecret: Please define a `secret`.. Read more at https://errors.authjs.dev#missingsecret" ],`
> > ```
> >  .dev.vars file is present,
> >  
> >  created by `bun run setup` with proper values
> > ```
> 
> make .env.local file and add AUTH_SECRET=you-secret-key

Tried, still the same error.
weird

**Comment by codingforfoodllc** [comment]
Did you figure this out? I am able to log in via google, but when I go to cloudflare and look at the DB, there are no users in it.

**Comment by Dhravya** [comment]
> Did you figure this out? I am able to log in via google, but when I go to cloudflare and look at the DB, there are no users in it.

Hi @codingforfoodllc - when you run it locally, the database changes also occur locally. There's a `.wrangler` folder which has a `.sqlite` file with the raw local database.
