### ISSUE TITLE
Missing Opensource license

### ISSUE THREAD

**Issue by AntCas** [Dhravya/cloudflare-saas-stack#33]
Please add a permissive license so that we can use this repo as a jumping off point for startup ideas. e.g. NextJS uses MIT License: https://github.com/vercel/next.js/blob/canary/license.md

**Comment by Dhravya** [comment]
Done!

**Comment by AntCas** [comment]
Thanks!

**Comment by fakerybakery** [comment]
Hi,
It looks like the license got deleted. Would it be possible to add it back?
Thanks!

**Comment by Hades32** [comment]
@Dhravya seems the LICENSE fil was deleted by accident, since no commit since its addition indicates it was done on purpose. Can we get it back?
