### ISSUE TITLE
Where to create new pages?

### ISSUE THREAD

**Issue by AntCas** [Dhravya/cloudflare-saas-stack#34]
It's been awhile since I've used NextJS, please forgive me if this is a dumb question:

Where do I add new routes?

If I e.g. want to create e.g. localhost:3000/hello where should that go?

I've tried:

```
/apps/web/hello.tsx
/apps/web/app/hello.tsx
/apps/web/app/pages/hello.tsx
/apps/web/pages/hello.tsx
```

The Next docs seem to diverge from this project structure 
https://nextjs.org/docs/app/building-your-application/routing

**Comment by AntCas** [comment]
Okay, I got it working by making the file:

`/apps/web/app/hello/page.tsx`

Is it required that each route-handling file be named page.tsx?

**Comment by Dhravya** [comment]
Yeah! It's just like a normal nextjs project
