### ISSUE TITLE
unable to run drizzle kit commands

### ISSUE THREAD

**Issue by codingforfoodllc** [Dhravya/cloudflare-saas-stack#36]
This might be user error on my part, but i am not able to run drizzle-kit commands like push or studio. For example, when i run 
`bunx drizzle-kit studio`
drizzle.config.json doesn't exist

Feels like i am doing something wrong, but not sure what.

**Comment by curtis-allan** [comment]
Make sure your drizzle.config file is in the root of the project directory where you're running the cli command. Also, heads up that the folder you've covered up is visible in the error log underneath.

**Comment by codingforfoodllc** [comment]
omg you are right, was in the right directory... Not used to working with monorepos or bun...  I am now getting this error though when running 'bunx drizzle-kit studio':
"Invalid input  Either "turso", "libsql", "better-sqlite" are available options for "--driver" "
Does bun need a different syntax?

**Comment by curtis-allan** [comment]
I've opened up a discussion about getting drizzle-kit studio to work when using D1, for both local and remote databases, and linked a Github comment that provided a working solution for me. If you only want to run studio off the local database, you will need to install a driver to run it. Bun comes equipped with its own Sqlite driver, however I have not been able to get this working as of yet. Just run `bun add -D better-sqlite3` and you should be good to go.

**Comment by Dhravya** [comment]
Fixed in #20, thanks!
