### ISSUE TITLE
A Monorepo Cloudflare Template

### ISSUE THREAD

**Issue by Abood2284** [Dhravya/cloudflare-saas-stack#54]
Thank you @Dhravya for open sourcing supermemory
i got to learn soo much from it,

i was exploring turbo repo and i just knew that you are the guy for this, as supermemory is built on this.

**by any chance you have a cloudflare stack template that also supports turbo repo? ( i know you did have in the beginning, unable to find now)**

**Comment by Dhravya** [comment]
hi! Yes, if you go through the repo history you will find the turbo repo implementation. i removed it for further simplicity.

**Comment by Abood2284** [comment]
Thank you found it.

**Comment by 2-fly-4-ai** [comment]
Did you manage to figure this out?

**Comment by 2-fly-4-ai** [comment]
> hi! Yes, if you go through the repo history you will find the turbo repo implementation. i removed it for further simplicity.

Any change you could make a turorepo version with expo as well? Or recommend how I could do that.

**Comment by Dhravya** [comment]
I will build another one using turborepo + expo

Dhravya Shah
https://dhravya.dev

**Comment by 2-fly-4-ai** [comment]
> I will build another one using turborepo + expo
> 
> Dhravya Shah
> https://dhravya.dev
> […](#)

I'm currently building a version with TRPC using your template as the base. Just trying to figure out what the best approach is. I think you have to share the API between the expo and next app, then share the types through the mono repo setup. I've used t3-turbo in the past and it's been pretty great.

Think this might be a solid starting point: https://github.com/trpc/trpc/tree/next/examples/cloudflare-workers. You can add you cloudflare services bindings to the workers(d1, r2 etc). Then somehow share it through there. 

This might help: https://github.com/2-fly-4-ai/cloudflare-saas-stack.git
