### ISSUE TITLE
Error after first deploy

### ISSUE THREAD

**Issue by abaudhuin** [Dhravya/cloudflare-saas-stack#8]
![image](https://github.com/user-attachments/assets/53e37a99-49ef-4e01-a8b4-359eb16ce629)

After a first deploy i still get an error. I'm not too familiar with this env so I'm not sure where to check. 

Everything logs ok in real time logs too:

![image](https://github.com/user-attachments/assets/9a82b606-85a3-42a0-9d90-358a704e6a9b)

Any idea why ?

**Comment by DiogoDuart3** [comment]
Same here, must be something to do with the wrangler file that sets up the database

**Comment by Dhravya** [comment]
Yeah! I think this is because the remote database migrations aren't there i guess?
I'm looking into it. Thanks for letting me know

**Comment by DiogoDuart3** [comment]
Nah, by following the readme it will run the migrations on the cloudflare database and it works locally, its the cloudflare deployment that didnt read that file i guess

**Comment by DiogoDuart3** [comment]
The latest version of drizzle orm removed the driver "d1" and now has "d1-http"

**Comment by Dhravya** [comment]
Right, makes sense :) 

there's a PR by @codetorso which i'll merge soon but that's the steps to fix it!

**Comment by abaudhuin** [comment]
Great. Feels kinda weird that there is no error anywhere though

**Comment by DiogoDuart3** [comment]
This is the error from the cloudflare functions
![image](https://github.com/user-attachments/assets/9b9a24da-0828-4e2c-a693-bb76b4d23b8c)

**Comment by Dhravya** [comment]
When you run it locally, the database used is actually a local sqlite instance.
When deployed, it uses a remote version of the same database.

`cd apps/web && wrangler d1 execute ${YOUR-DATABASE-NAME} --file=migrations/0000_setup.sql --remote`

**Comment by Dhravya** [comment]
I fixed this issue in the setup script

**Comment by DiogoDuart3** [comment]
Running "bunx wrangler d1 migrations apply DB_NAME --remote" worked

**Comment by Dhravya** [comment]
Perfect!

**Comment by Dhravya** [comment]
@abaudhuin can you confirm this too?

**Comment by abaudhuin** [comment]
yes, I confirm it's deployed now!
Thanks
